apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: discovery
    installationId: {{ include "gloo.installationId" . }}
  name: discovery
  namespace: {{ $.Release.Namespace }}