{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: gateway
    installationId: {{ include "gloo.installationId" . }}
  name: gateway
  namespace: {{ $.Release.Namespace }}
{{ end }}
