{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: gateway
    installationId: {{ include "gloo.installationId" . }}
  name: gateway
  namespace: {{ $.Release.Namespace }}


{{- if and .Values.gateway.validation.enabled .Values.gateway.certGenJob.enabled }}
---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: gateway
    installationId: {{ include "gloo.installationId" . }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "5" # must come before cert-gen job
  name: gateway-certgen
  namespace: {{ $.Release.Namespace }}
{{ end }}

{{ end }}
